language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=4.2.1"
  - "RAILS_VERSION=master"
gemfile:
  - listings.gemfile
before_script:
  - bundle install
script:
  - bundle exec rake test
